export const Trained = Object.freeze({
    UNTRAINED: 0,
    TRAINED: 1,
    EXPERT: 2,
    MASTERY: 3
})

export const Descriptor = Object.freeze({
    MOVEMENT: "Movement",
    CRAFTING: "Crafting",
    EXPLORATION: "Exploration",
    INTERACTION: "Interaction",
    INVESTIGATION: "Investigation",
    OPERATOR: "Operator",
})

export const Type = Object.freeze({
    BASIC: 'Basic',
    ADVANCED: 'Advanced'
})

export class Skill {
    constructor(name, type, characteristic, descriptor) {
        this.name = name,
        this.type = type,
        this.characteristic = characteristic,
        this.descriptor = descriptor
        this.trained = Trained.UNTRAINED
    }
}

export let skills = [
    new Skill('Acrobatics', Type.ADVANCED, 'ag', Descriptor.MOVEMENT),
    new Skill('Awareness', Type.BASIC, 'per', Descriptor.EXPLORATION),
    new Skill('Barter', Type.BASIC, 'fel', Descriptor.INTERACTION),
    new Skill('Blather', Type.ADVANCED, 'fel', Descriptor.INTERACTION),
    new Skill('Carouse', Type.BASIC, 't', null),
    new Skill('Charm', Type.BASIC, 'fel', Descriptor.INTERACTION),
    new Skill('Chem-Use', Type.ADVANCED, 'int', 'Crafting Investigation'),
    new Skill('Ciphers (Rogue Trader)', Type.ADVANCED, 'int', null), 
    new Skill('Ciphers (Mercenary Cant)', Type.ADVANCED, 'int', null), 
    new Skill('Ciphers (Nobilite Family)', Type.ADVANCED, 'int', null), 
    new Skill('Ciphers (Astropath Sign)', Type.ADVANCED, 'int', null), 
    new Skill('Ciphers (Underworld)', Type.ADVANCED, 'int', null), 
    new Skill('Climb', Type.BASIC, 's', Descriptor.MOVEMENT),
    new Skill('Commerce', Type.ADVANCED, 'fel', null),
    new Skill('Command', Type.BASIC, 'fel', Descriptor.INTERACTION),
    new Skill('Common Lore (Adeptus Arbites)', Type.ADVANCED, 'int', Descriptor.INVESTIGATION), 
    new Skill('Common Lore (Adeptus Astra Telepathica)', Type.ADVANCED, 'int', Descriptor.INVESTIGATION), 
    new Skill('Common Lore (Adeptus Mechanicus)', Type.ADVANCED, 'int', Descriptor.INVESTIGATION), 
    new Skill('Common Lore (Administratum)', Type.ADVANCED, 'int', Descriptor.INVESTIGATION), 
    new Skill('Common Lore (Ecclesiarchy)', Type.ADVANCED, 'int', Descriptor.INVESTIGATION), 
    new Skill('Common Lore (Imperial Creed)', Type.ADVANCED, 'int', Descriptor.INVESTIGATION), 
    new Skill('Common Lore (Imperial Guard)', Type.ADVANCED, 'int', Descriptor.INVESTIGATION), 
    new Skill('Common Lore (Imperial Navy)', Type.ADVANCED, 'int', Descriptor.INVESTIGATION), 
    new Skill('Common Lore (Imperium)', Type.ADVANCED, 'int', Descriptor.INVESTIGATION), 
    new Skill('Common Lore (Koronous Expanse)', Type.ADVANCED, 'int', Descriptor.INVESTIGATION), 
    new Skill('Common Lore (Navis Nobilite)', Type.ADVANCED, 'int', Descriptor.INVESTIGATION), 
    new Skill('Common Lore (Rogue Traders)', Type.ADVANCED, 'int', Descriptor.INVESTIGATION), 
    new Skill('Common Lore (Tech)', Type.ADVANCED, 'int', Descriptor.INVESTIGATION), 
    new Skill('Common Lore (War)', Type.ADVANCED, 'int', Descriptor.INVESTIGATION), 
    new Skill('Concealment', Type.BASIC, 'ag', null),
    new Skill('Contortionist', Type.BASIC, 'ag', Descriptor.MOVEMENT),
    new Skill('Deceive', Type.BASIC, 'fel', Descriptor.INTERACTION),
    new Skill('Demolition', Type.ADVANCED, 'int', Descriptor.CRAFTING),
    new Skill('Disguise', Type.BASIC, 'fel', null),
    new Skill('Dodge', Type.BASIC, 'ag', null),
    new Skill('Drive (Ground Vehicle)', Type.ADVANCED, 'ag', Descriptor.OPERATOR), 
    new Skill('Drive (Skimmer/Hover)', Type.ADVANCED, 'ag', Descriptor.OPERATOR), 
    new Skill('Drive (Walker)', Type.ADVANCED, 'ag', Descriptor.OPERATOR), 
    new Skill('Evaluate', Type.BASIC, 'int', Descriptor.INVESTIGATION),
    new Skill('Forbidden Lore (Adeptus Mechanicus)', Type.ADVANCED, 'int', Descriptor.INVESTIGATION), 
    new Skill('Forbidden Lore (Archeotech)', Type.ADVANCED, 'int', Descriptor.INVESTIGATION), 
    new Skill('Forbidden Lore (Daemonology)', Type.ADVANCED, 'int', Descriptor.INVESTIGATION), 
    new Skill('Gamble', Type.BASIC, 'int', null),
    new Skill('Inquiry', Type.BASIC, 'fel', Descriptor.INVESTIGATION),
    new Skill('Interrogation', Type.ADVANCED, 'wp', Descriptor.INVESTIGATION),
    new Skill('Intimidate', Type.BASIC, 's', Descriptor.INTERACTION),
    new Skill('Invocation', Type.ADVANCED, 'wp', null),
    new Skill('Literacy', Type.ADVANCED, 'int', null),
    new Skill('Logic', Type.BASIC, 'int', Descriptor.INVESTIGATION),
    new Skill('Medicae', Type.ADVANCED, 'int', null),
    new Skill('Navigation (Surface)', Type.ADVANCED, 'int', Descriptor.EXPLORATION), 
    new Skill('Navigation (Stellar)', Type.ADVANCED, 'int', Descriptor.EXPLORATION), 
    new Skill('Navigation (Warp)', Type.ADVANCED, 'int', Descriptor.EXPLORATION), 
    new Skill('Performer (Dancer)', Type.ADVANCED, 'fel', null),
    new Skill('Performer (Musician)', Type.ADVANCED, 'fel', null),
    new Skill('Performer (Singer)', Type.ADVANCED, 'fel', null),
    new Skill('Performer (Storyteller)', Type.ADVANCED, 'fel', null),
    new Skill('Pilot (Personal)', Type.ADVANCED, 'ag', Descriptor.OPERATOR),
    new Skill('Pilot (Flyers)', Type.ADVANCED, 'ag', Descriptor.OPERATOR),
    new Skill('Pilot (Space Craft)', Type.ADVANCED, 'ag', Descriptor.OPERATOR),
    new Skill('Psyniscience', Type.ADVANCED, 'per', null),
    new Skill('Scholastic Lore (Archaic)', Type.ADVANCED, 'int', Descriptor.INVESTIGATION),
    new Skill('Scholastic Lore (Astromancy)', Type.ADVANCED, 'int', Descriptor.INVESTIGATION),
    new Skill('Scholastic Lore (Beasts)', Type.ADVANCED, 'int', Descriptor.INVESTIGATION),
    new Skill('Scholastic Lore (Bureaucracy)', Type.ADVANCED, 'int', Descriptor.INVESTIGATION),
    new Skill('Scholastic Lore (Chymistry)', Type.ADVANCED, 'int', Descriptor.INVESTIGATION),
    new Skill('Scholastic Lore (Cryptology)', Type.ADVANCED, 'int', Descriptor.INVESTIGATION),
    new Skill('Scholastic Lore (Heraldry)', Type.ADVANCED, 'int', Descriptor.INVESTIGATION),
    new Skill('Scholastic Lore (Imperial Warrants)', Type.ADVANCED, 'int', Descriptor.INVESTIGATION),
    new Skill('Scholastic Lore (Imperial Creed)', Type.ADVANCED, 'int', Descriptor.INVESTIGATION),
    new Skill('Scholastic Lore (Judgement)', Type.ADVANCED, 'int', Descriptor.INVESTIGATION),
    new Skill('Scholastic Lore (Legend)', Type.ADVANCED, 'int', Descriptor.INVESTIGATION),
    new Skill('Scholastic Lore (Navis Nobilite)', Type.ADVANCED, 'int', Descriptor.INVESTIGATION),
    new Skill('Scholastic Lore (Numerology)', Type.ADVANCED, 'int', Descriptor.INVESTIGATION),
    new Skill('Scholastic Lore (Occult)', Type.ADVANCED, 'int', Descriptor.INVESTIGATION),
    new Skill('Scholastic Lore (Philosophy)', Type.ADVANCED, 'int', Descriptor.INVESTIGATION),
    new Skill('Scholastic Lore (Tactica Imperialis)', Type.ADVANCED, 'int', Descriptor.INVESTIGATION),
    new Skill('Scrutiny', Type.BASIC, 'per', null),
    new Skill('Search', Type.BASIC, 'per', Descriptor.EXPLORATION),
    new Skill('Secret Tongue (Administratum)', Type.ADVANCED, 'int', null),
    new Skill('Secret Tongue (Ecclesiarchy)', Type.ADVANCED, 'int', null),
    new Skill('Secret Tongue (Military)', Type.ADVANCED, 'int', null),
    new Skill('Secret Tongue (Navigator)', Type.ADVANCED, 'int', null),
    new Skill('Secret Tongue (Rogue Trader)', Type.ADVANCED, 'int', null),
    new Skill('Secret Tongue (Tech)', Type.ADVANCED, 'int', null),
    new Skill('Secret Tongue (Underdeck)', Type.ADVANCED, 'int', null),
    new Skill('Security', Type.ADVANCED, 'ag', Descriptor.EXPLORATION),
    new Skill('Shadowing', Type.ADVANCED, 'ag', null),
    new Skill('Silent Move', Type.BASIC, 'ag', null),
    new Skill('Sleight of Hand', Type.ADVANCED, 'ag', null),
    new Skill('Speak Language (Eldar)', Type.ADVANCED, 'int', null),
    new Skill('Speak Language (Explorator Binary)', Type.ADVANCED, 'int', null),
    new Skill('Speak Language (High Gothic)', Type.ADVANCED, 'int', null),
    new Skill('Speak Language (Low Gothic)', Type.ADVANCED, 'int', null),
    new Skill('Speak Language (Ork)', Type.ADVANCED, 'int', null),
    new Skill('Speak Language (Techna-Lingua)', Type.ADVANCED, 'int', null),
    new Skill('Speak Language (Trader\'s Cant)', Type.ADVANCED, 'int', null),
    new Skill('Survival', Type.ADVANCED, 'int', Descriptor.EXPLORATION),
    new Skill('Swim', Type.BASIC, 's', Descriptor.MOVEMENT),
    new Skill('Tech-Use', Type.ADVANCED, 'int', Descriptor.EXPLORATION),
    new Skill('Tracking', Type.ADVANCED, 'int', Descriptor.EXPLORATION),
    new Skill('Trade (Archaeologist)', Type.ADVANCED, 'int', 'Crafting Exploration'),
    new Skill('Trade (Armourer)', Type.ADVANCED, 'ag', 'Crafting Exploration'),
    new Skill('Trade (Astrographer)', Type.ADVANCED, 'int', 'Crafting Exploration'),
    new Skill('Trade (Chymist)', Type.ADVANCED, 'int', 'Crafting Exploration'),
    new Skill('Trade (Cryptographer)', Type.ADVANCED, 'int', 'Crafting Exploration'),
    new Skill('Trade (Explorator)', Type.ADVANCED, 'int', 'Crafting Exploration'),
    new Skill('Trade (Linguist)', Type.ADVANCED, 'int', 'Crafting Exploration'),
    new Skill('Trade (Remembrancer)', Type.ADVANCED, 'ag int', 'Crafting Exploration'),
    new Skill('Trade (Shipwright)', Type.ADVANCED, 'int', 'Crafting Exploration'),
    new Skill('Trade (Soothsayer)', Type.ADVANCED, 'fel', 'Crafting Exploration'),
    new Skill('Trade (Technomat)', Type.ADVANCED, 'int', 'Crafting Exploration'),
    new Skill('Trade (Trader)', Type.ADVANCED, 'fel', 'Crafting Exploration'),
    new Skill('Trade (Voidfarer)', Type.ADVANCED, 'ag', 'Crafting Exploration'),
    new Skill('Wrangling', Type.ADVANCED, 'int', null)
]

