 export class Talent {
    constructor(name, charReq, skillReq, talentReq, gearReq, benefit) {
        this.name = name;
        this.charReq = charReq;
        this.skillReq = skillReq;
        this.talentReq = talentReq;
        this.gearReq = gearReq;
        this.benefit = benefit;
    }
}

export let talents = [
    new Talent('Air of Authority', {'Fel': 30}, null, null, null, 'Affect more targets with Test.'),
    new Talent('Ambidextrous', {'Ag': 30}, null, null, null, 'Use either hand equally well.'),
    new Talent('Armour of Contempt', {'WP': 40}, null, null, null, 'The Explorer is resistant to corruption.'),
    new Talent('Assassin Strike', {'Ag': 40}, ['Acrobatic'], null, null, 'On a successful Acrobatics Test after making a melee attack, the Explorer may move as a Free Action.'),
    new Talent('Autosanguine', null, null, null, null, 'Heal 2 damage/day, always Lightly Wounded.'),
    new Talent('Basic Weapon Training (Bolt)', null, null, null, null, 'Use weapon group without penalty.'), 
    new Talent('Basic Weapon Training (Las)', null, null, null, null, 'Use weapon group without penalty.'), 
    new Talent('Basic Weapon Training (Launcher)', null, null, null, null, 'Use weapon group without penalty.'), 
    new Talent('Basic Weapon Training (Primitive)', null, null, null, null, 'Use weapon group without penalty.'), 
    new Talent('Basic Weapon Training (SP)', null, null, null, null, 'Use weapon group without penalty.'), 
    new Talent('Basic Weapon Training (Universal)', null, null, null, null, 'Use weapon group without penalty.'), 
    new Talent('Bastion of Iron Will', {'WP': 40}, null, ['Psy Rating', 'Strong Minded'], null, 'Double Defensive Psy Rating for Opposed Tests.'),
    new Talent('Battle Rage', null, null, ['Frenzy'], null, 'Parry while Frenzied.'),
    new Talent('Berserk Charge', null, null, null, null, 'Gain +20 bonus when charging.'),
    new Talent('Binary Chatter', null, null, null, null, '+10 bonus to control servitors.'),
    new Talent('Blademaster', {'WS': 30}, null, ['Melee Weapon Training'], null, 'Re-roll missed attack, once per Round.'),
    new Talent('Blessed Radiance', null, null, ['Pure Faith', 'Divine Ministration', 'The Emperor Protects', 'Wrath of the Righteous'], null, 'Extends Faith Powers to allies.'),
    new Talent('Blind Fighting', {'Per': 30}, null, null, null, 'Suffer half the usual penalties when vision is obscured.'),
    new Talent('Bloodtracker', null, null, null, null, 'Receive benefits for capturing bounties.'),
    new Talent('Bulging Biceps', {'S': 45}, null, null, null, 'Remove bracing requirement for certain weapons.'),
    new Talent('Catfall', {'Ag': 30}, null, null, null, 'Reduce falling Damage.'),
    new Talent('Chem Geld', null, null, null, null, 'Immune to seduction, resistant to charm.'),
    new Talent('Cleanse and Purify', null, null, ['Flame Weapon Training (Universal)'], null, 'Penalty to avoid being hit by the Explorer\'s flamer attacks.'),
    new Talent('Combat Formation', {'Int': 40}, null, null, null, 'Use Intelligence Bonus for initiative.'),
    new Talent('Combat Master', {'WS': 30}, null, null, null, 'Opponents get no bonus for outnumbering the Explorer.'),
    new Talent('Combat Sense', {'Per': 40}, null, null, null, 'Use Per Bonus instead of Ag Bonus for Initiative.'),
    new Talent('Concealed Cavity', null, null, null, null, 'The Explorer has a secret compartment on his person.'),
    new Talent('Counter Attack', {'WS': 40}, null, null, null, 'Gain free attack with successful Parry.'),
    new Talent('Crack Shot', {'BS': 40}, null, null, null, 'Deal +2 Critical Damgae with ranged weapons.'),
    new Talent('Crippling Strike', {'WS': 50}, null, null, null, 'Deal +4 Critical Damage with melee weapons.'),
    new Talent('Crushing Blow', {'S': 40}, null, null, null, 'Deal +2 Damage with melee weapons.'),
    new Talent('Dark Soul', null, null, null, null, 'Take half the penalty on Malignancy Tests.'),
    new Talent('Deadeye Shot', {'BS': 30}, null, null, null, 'Called shots are at -10 penalty.'),
    new Talent('Decadence', {'T': 30}, null, null, null, 'Gain uncanny resistance to drugs and alcohol.'),
    new Talent('Die Hard', {'WP': 40}, null, null, null, 'Re-roll death chance incurred by blood loss.'),
    new Talent('Disarm', {'Ag': 30}, null, null, null, 'Force opponent to drop weapon.'),
    new Talent('Disturbing Voice', null, null, null, null, '+10 bonus to Intimidate and Interrogation, -10 penalty to Fel.'),
    new Talent('Divine Ministration', null, null, ['Pure Faith'], null, 'Spend a Fate Point to remove Fatigue or heal.'),
    new Talent('Double Team', null, null, null, null, 'Gain additional +10 bonus for ganging up.'),
    new Talent('Dual Shot', {'Ag': 40}, null, ['Two-Weapon Wielder (Ballistic)'], null, 'One Ballistic Skill Test hits target twice.'),
    new Talent('Dual Strike', {'Ag': 40}, null, ['Two-Weapon Wielder (Melee)'], null, 'One Weapon Skill Test hits target twice.'),
    new Talent('Duty Unto Death', {'WP': 45}, null, null, null, 'Temporarily ignore injuries.'),
    new Talent('Electrical Succour', null, null, null, ['Mechanicus Implants'], '+10 bonus to T Tests to remove Fatigue.'),
    new Talent('Electro Graft Use', null, null, null, null, '+10 bonus to Inquiry, Tech-Use, Common Knowledge.'),
    new Talent('Enemy (Academics)', null, null, null, null, 'Academics particularly despises the Explorer.'), 
    new Talent('Enemy (Adepta Sororitas)', null, null, null, null, 'Adepta Sororitas particularly despises the Explorer.'), 
    new Talent('Enemy (Adeptus Arbites)', null, null, null, null, 'Adeptus Arbites particularly despises the Explorer.'), 
    new Talent('Enemy (Adeptus Mechanicus)', null, null, null, null, 'Adeptus Mechanicus particularly despises the Explorer.'), 
    new Talent('Enemy (Administratum)', null, null, null, null, 'The Administratum particularly despises the Explorer.'), 
    new Talent('Enemy (Astropaths)', null, null, null, null, 'Astropaths particularly despises the Explorer.'), 
    new Talent('Enemy (Ecclesiarchy)', null, null, null, null, 'The Ecclesiarchy particularly despises the Explorer.'), 
    new Talent('Enemy (Government)', null, null, null, null, 'A Government particularly despises the Explorer.'), 
    new Talent('Enemy (Imperial Guard)', null, null, null, null, 'The Imperial Guard particularly despises the Explorer.'), 
    new Talent('Enemy (Imperial Navy)', null, null, null, null, 'The Imperial Navy particularly despises the Explorer.'), 
    new Talent('Enemy (Inquisition)', null, null, null, null, 'The Inquisition particularly despises the Explorer.'), 
    new Talent('Enemy (Military)', null, null, null, null, 'A Military particularly despises the Explorer.'), 
    new Talent('Enemy (Navigators)', null, null, null, null, 'Navigators particularly despises the Explorer.'), 
    new Talent('Enemy (Nobility)', null, null, null, null, 'Nobility particularly despises the Explorer.'), 
    new Talent('Enemy (Rogue Trader)', null, null, null, null, 'A Rogue Trader particularly despises the Explorer.'), 
    new Talent('Enemy (Underworld)', null, null, null, null, 'The Underworld particularly despises the Explorer.'), 
    new Talent('Enemy (Workers)', null, null, null, null, 'Workers particularly despises the Explorer.'), 
    new Talent('Energy Cache', null, null, null, ['Mechanicus Implants'], 'Luminen Blast, Charge, and Shock Fatigue-free.'),
    new Talent('Enhanced Bionic Frame', null, null, ['Machinator Array'], null, 'The Explorer gains the Auto-stabilised Trait.'),
    new Talent('Exotic Weapon Training', null, null, null, null, 'Gain proficienct with an exotic weapon type.'), 
    new Talent('Favoured by the Warp', {'WP': 35}, null, null, null, 'Roll twice for Psychic Phenomena and take better result.'),
    new Talent('Fearless', null, null, null, null, 'Immune to fear and pinning.'),
    new Talent('Feedback Screech', null, null, null, ['Mechanicus Implants'], '30m radius, test WP or lose Half Action.'),
    new Talent('Ferric Lure', null, null, null, ['Mechanicus Implants'], 'WP Test to call 1kg/WP Bonus of metal objects.'),
    new Talent('Ferric Summons', null, null, ['Ferric Lure'], "Mechanicus Implants", 'WP Test to call 2kg/WP Bonus of metal objects.'),
    new Talent('Flame Weapon Training (Universal)', null, null, null, null, 'Gain proficiency with a group of flame weapons.'), 
    new Talent('Foresight', {'Int': 30}, null ,null, null, 'Contemplate to gain +10 bonus on next Test.'),
    new Talent('Frenzy', null, null, null, null, 'Enter psychotic rage to gain combat bonuses.'),
    new Talent('Furious Assualt', {'WS': 35}, null, null, null, 'On a successful WS Test, gain a free second attack.'),
    new Talent('Good Reputation (Academics)', {'Fel': 50}, null, ['Peer'], null, 'The Explorer has a good reputation amongst Academics.'), 
    new Talent('Good Reputation (Adeptus Arbites)', {'Fel': 50}, null, ['Peer'], null, 'The Explorer has a good reputation amongst The Adeptus Arbites.'), 
    new Talent('Good Reputation (Adeptus Mechanicus)', {'Fel': 50}, null, ['Peer'], null, 'The Explorer has a good reputation amongst The Adeptus Mechanicus.'), 
    new Talent('Good Reputation (Administratum)', {'Fel': 50}, null, ['Peer'], null, 'The Explorer has a good reputation amongst the Administratum.'), 
    new Talent('Good Reputation (Astropaths)', {'Fel': 50}, null, ['Peer'], null, 'The Explorer has a good reputation amongst Astropaths.'), 
    new Talent('Good Reputation (Ecclesiarchy)', {'Fel': 50}, null, ['Peer'], null, 'The Explorer has a good reputation amongst The Ecclesiarchy.'), 
    new Talent('Good Reputation (Feral Worlders)', {'Fel': 50}, null, ['Peer'], null, 'The Explorer has a good reputation amongst Feral Worlders.'), 
    new Talent('Good Reputation (Government)', {'Fel': 50}, null, ['Peer'], null, 'The Explorer has a good reputation amongst a Government.'), 
    new Talent('Good Reputation (Hivers)', {'Fel': 50}, null, ['Peer'], null, 'The Explorer has a good reputation amongst Hivers.'), 
    new Talent('Good Reputation (Imperial Guard)', {'Fel': 50}, null, ['Peer'], null, 'The Explorer has a good reputation amongst The Imperial Guard.'), 
    new Talent('Good Reputation (Imperial Navy)', {'Fel': 50}, null, ['Peer'], null, 'The Explorer has a good reputation amongst The Imperial Navy.'), 
    new Talent('Good Reputation (Inquisition)', {'Fel': 50}, null, ['Peer'], null, 'The Explorer has a good reputation amongst The Inquisition.'), 
    new Talent('Good Reputation (Middle Classes)', {'Fel': 50}, null, ['Peer'], null, 'The Explorer has a good reputation amongst The Middle Classes.'), 
    new Talent('Good Reputation (Nobility)', {'Fel': 50}, null, ['Peer'], null, 'The Explorer has a good reputation amongst Nobility.'),
    new Talent('Good Reputation (The Insane)', {'Fel': 50}, null, ['Peer'], null, 'The Explorer has a good reputation amongst The Insane.'), 
    new Talent('Good Reputation (Void Born)', {'Fel': 50}, null, ['Peer'], null, 'The Explorer has a good reputation amongst Void Born.'), 
    new Talent('Good Reputation (Workers)', {'Fel': 50}, null, ['Peer'], null, 'The Explorer has a good reputation amongst Workers.'), 
    new Talent('Good Reputation (Underworld)', {'Fel': 50}, null, ['Peer'], null, 'The Explorer has a good reputation amongst The Underworld.'), 
    new Talent('Guardian', {'Ag': 40}, null, null, null, 'Switch location with an ally.'),
    new Talent('Gun Blessing', null, null, null, ['Mechanicus Implants'], 'Un-jam Int Bonus guns in 10m radius.'),
    new Talent('Gunslinger', {'BS': 40}, null, ['Two-Weapon Wielder (Ballistic)'], null, 'Fighting with two pistols incurs only -10 penalty.'),
    new Talent('Hard Bargain', null, null, null, null, 'Gain +1 to Profit Factor.'),
    new Talent('Hard Target', {'Ag': 40}, null, null, null, 'Opponents take -20 to BS Tests when the Explorer charges or runs.'),
    new Talent('Hardy', {'T': 40}, null, null, null, 'The Explorer always heals as if Lightly Wounded.'),
    new Talent('Hatred (Criminals)', null, null, null, null, 'Gain +10 bonus to attack hated creatures.'), 
    new Talent('Hatred (Specific Rogue Trader)', null, null, null, null, 'Gain +10 bonus to attack hated creatures.'), 
    new Talent('Hatred (Pirates)', null, null, null, null, 'Gain +10 bonus to attack hated creatures.'), 
    new Talent('Hatred (Specific Xeno)', null, null, null, null, 'Gain +10 bonus to attack hated creatures.'), 
    new Talent('Hatred (Psykers)', null, null, null, null, 'Gain +10 bonus to attack hated creatures.'), 
    new Talent('Hatred (Mutants)', null, null, null, null, 'Gain +10 bonus to attack hated creatures.'), 
    new Talent('Heavy Weapon Training (Bolt)', null, null, null, null, 'Gain proficiency with a heavy weapon group.'), 
    new Talent('Heavy Weapon Training (Flame)', null, null, null, null, 'Gain proficiency with a heavy weapon group.'), 
    new Talent('Heavy Weapon Training (Las)', null, null, null, null, 'Gain proficiency with a heavy weapon group.'), 
    new Talent('Heavy Weapon Training (Launcher)', null, null, null, null, 'Gain proficiency with a heavy weapon group.'), 
    new Talent('Heavy Weapon Training (Melta)', null, null, null, null, 'Gain proficiency with a heavy weapon group.'), 
    new Talent('Heavy Weapon Training (Plasma)', null, null, null, null, 'Gain proficiency with a heavy weapon group.'), 
    new Talent('Heavy Weapon Training (Primitive)', null, null, null, null, 'Gain proficiency with a heavy weapon group.'), 
    new Talent('Heavy Weapon Training (SP)', null, null, null, null, 'Gain proficiency with a heavy weapon group.'), 
    new Talent('Heightened Senses', null, null, null, null, 'Gain +10 bonus to particular sense.'),
    new Talent('Hip Shooting', {'BS': 40, 'Ag': 40}, null, null, null, 'Gain a free attack when the Explorer moves.'),
    new Talent('Hotshot Pilot', {'Ag': 40}, ['Pilot (Personal)', 'Pilot (Flyers)', 'Pilot (Space Craft)'], null, null, 'All Pilot Skills are Basic Skills.'),
    new Talent('Improved Warp Sense', null, null, ['Warp Sense'], null, 'Allows Psynisciences Test as Free Action.'),
    new Talent('Independent Targeting', {'BS': 40}, null, null, null, 'Fire at two or more targets further than 10m apart.'),
    new Talent('Infused Knowledge', {'Int': 40}, null, null, null, 'Treat Common and Scholastic Lore as Basic Skills.'),
    new Talent('Inspire Wrath', {'Fel': 30}, null, null, null, 'Inspires crowds to anger.'),
    new Talent('Into the Jaws of Hell', null, null, ['Iron Discipline'], null, 'Minions gain immunity to pinning and fear whilst in the Explorer\'s prescence.'),
    new Talent('Iron Discipline', {'WP': 30}, ['Command'], null, null, 'Minions can re-roll fear and pinning Tests.'),
    new Talent('Iron Jaw', {'T': 40}, null, null, null, 'Test Toughness to overcome stunning.'),
    new Talent('Jaded', {'WP': 30}, null, null, null, 'Never gain IP from ordinary horrors.'),
    new Talent('Last Man Standing', null, null, ['Nerves of Steel'], null, 'Immune to Pinning by Pistols and Basic Weapons. Improves Cover.'),
    new Talent('Leap Up', {'Ag': 30}, null, null, null, null, 'Stand up as a Free Action.'),
    new Talent('Light Sleeper', {'Per': 30}, null, null, null, 'Counts as awake, even when asleep.'),
    new Talent('Lightning Attack', null, null, ['Swift Attack'], null, 'Attack three times with a Full Action.'),
    new Talent('Lightning Reflexes', null, null, null, null, 'Add twice AB to Initiative rolls.'),
    new Talent('Litany of Hate', null, null, ['Hatred'], null, 'Extend benefits of Hatred to allies.'),
    new Talent('Logis Implant', null, null, null, null, '+10 bonus on WS and BS on successful Tech-Use Test.'),
    new Talent('Luminen Blast', null, null, null, ['Mechanicus Implants'], '1D10+WP Bonus Energy Damage Bolt. Causes Fatigue.'),
    new Talent('Luminen Charge', null, null, null, ['Mechanicus Implants'], 'T Test to power/charge tech. Causes Fatigue.'),
    new Talent('Luminen Shock', null, null, null, ['Mechanicus Implants'], '1D10+3 Energy Damage Shock. Causes Fatigue.'),
    new Talent('Machinator Array', null, null, null, ['Mechanicus Implants'], 'The Explorer has advanced Mechanicus augmetics.'),
    new Talent('Maglev Grace', null, null, null, ['Mechanicus Implants'], 'Hover 1D10+TB minutes once per day.'),
    new Talent('Maglev Transcendence', null, null, ['Maglev Grace'], ['Mechanicus Implants'], 'Hover 2D10+TB minutes twice per day.'),
    new Talent('Marksman', {'BS': 35}, null, null, null, 'No penalties for firing at long or extreme range.'),
    new Talent('Master & Commander', {'Int': 35, 'Fel': 35}, null, null, null, 'The Explorer\'s commands coordinate others in combat.'),
    new Talent('Master Chirurgeon', null, ['Medicae'], null, null, 'Perform advanced medical procedures.'), //
    new Talent('Master Engineer', null, ['Tech-Use'], null, ['Mechanicus Implants'], 'Use a Fate Point for automatic success.'), //
    new Talent('Master Orator', {'Fel': 30}, null, null, null, 'Affect 10 times the normal numbers with a Fellowship Test.'),
    new Talent('Mechadendrite Use (Weapon)', null, null, null, ['Mechanicus Implants'], 'The Explorer can use Weapon Mechadendrites.'), 
    new Talent('Mechadendrite Use (Utility)', null, null, null, ['Mechanicus Implants'], 'The Explorer can use Utility Mechadendrites.'), 
    new Talent('Meditation', null, null, null, null, 'The Explorer may enter a trance to remove Fatigue.'),
    new Talent('Melee Weapon Training (Primitive)', null, null, null, null, 'Gain proficiency with a group of melee weapons.'), 
    new Talent('Melee Weapon Training (Universal)', null, null, null, null, 'Gain proficiency with a group of melee weapons.'), 
    new Talent('Mighty Shot', {'BS': 40}, null, null, null, 'Deal +2 damage with ranged attacks.'),
    new Talent('Mimic', null, null, null, null, 'The Explorer can copy voices.'),
    new Talent('Navigator', null, null, null, null, 'The Explorer possesses the Navigator gene.'),
    new Talent('Navigator Power', null, null, ['Navigator'], null, 'Gain the ability to use a power within one of the Explorer\'s groups.'),
    new Talent('Nerves of Steel', null, null, null, null, 'Re-roll failed tests to avoid pinning.'),
    new Talent('Orthoproxy', null, null, null, null, '+20 bonus to resist mind control or interrogation.'),
    new Talent('Paranoia', null, null, null, null, 'The Explorer is alert for danger.'),
    new Talent('Peer (Academics)', {'Fel': 30}, null, null, null, 'Gain +10 bonus on Fel Tests to interact with Academics.'), 
    new Talent('Peer (Adeptus Arbites)', {'Fel': 30}, null, null, null, 'Gain +10 bonus on Fel Tests to interact with The Adeptus Arbites.'), 
    new Talent('Peer (Adeptus Mechanicus)', {'Fel': 30}, null, null, null, 'Gain +10 bonus on Fel Tests to interact with The Adeptus Mechanicus.'), 
    new Talent('Peer (Administratum)', {'Fel': 30}, null, null, null, 'Gain +10 bonus on Fel Tests to interact with The Administratum.'), 
    new Talent('Peer (Astropaths)', {'Fel': 30}, null, null, null, 'Gain +10 bonus on Fel Tests to interact with Astropaths.'), 
    new Talent('Peer (Ecclesiarchy)', {'Fel': 30}, null, null, null, 'Gain +10 bonus on Fel Tests to interact with The Ecclesiarchy.'), 
    new Talent('Peer (Feral Worlders)', {'Fel': 30}, null, null, null, 'Gain +10 bonus on Fel Tests to interact with Feral Worlders.'), 
    new Talent('Peer (Government)', {'Fel': 30}, null, null, null, 'Gain +10 bonus on Fel Tests to interact with a Government.'), 
    new Talent('Peer (Hivers)', {'Fel': 30}, null, null, null, 'Gain +10 bonus on Fel Tests to interact with Hivers.'), 
    new Talent('Peer (Inquisition)', {'Fel': 30}, null, null, null, 'Gain +10 bonus on Fel Tests to interact with The Inquisition.'), 
    new Talent('Peer (Middle Classes)', {'Fel': 30}, null, null, null, 'Gain +10 bonus on Fel Tests to interact with The Middle Classes.'), 
    new Talent('Peer (Military)', {'Fel': 30}, null, null, null, 'Gain +10 bonus on Fel Tests to interact with a Military.'), 
    new Talent('Peer (Nobility)', {'Fel': 30}, null, null, null, 'Gain +10 bonus on Fel Tests to interact with Nobility.'), 
    new Talent('Peer (The Insane)', {'Fel': 30}, null, null, null, 'Gain +10 bonus on Fel Tests to interact with The Insane.'), 
    new Talent('Peer (Underworld)', {'Fel': 30}, null, null, null, 'Gain +10 bonus on Fel Tests to interact with The Underworld.'), 
    new Talent('Peer (Void Born)', {'Fel': 30}, null, null, null, 'Gain +10 bonus on Fel Tests to interact with Void Born.'), 
    new Talent('Peer (Workers)', {'Fel': 30}, null, null, null, 'Gain +10 bonus on Fel Tests to interact with Workers.'), 
    new Talent('Pistol Weapon Training (Primitive)', null, null, null, null, 'Gain proficiency with a group of pistol weapons.'), 
    new Talent('Pistol Weapon Training (Universal)', null, null, null, null, 'Gain proficiency with a group of pistol weapons.'), 
    new Talent('Polyglot', {'Int': 30, 'Fel': 30}, null, null, null, 'The Explorer has an innate ability with languages.'),
    new Talent('Precise Blow', {'WS': 40}, null, ['Sure Strike'], null, 'No penalty for attacks against specific locations.'),
    new Talent('Prosanguine', null, null, null, null, 'Heal 1D5 Damage once per day.'),
    new Talent('Psy Rating', null, null, null, null, 'Become a more powerful Psyker, rated 1-10.'),
    new Talent('Psychic Discipline', null, null, null, null, 'Gain access to an additional Psychic Discipline.'),
    new Talent('Psychic Technique', null, null, null, null, 'Gain an extra Psychic Technique.'), 
    new Talent('Pure Faith', null, null, null, null, 'The Explorer is immune to Daemonic Presence.'),
    new Talent('Purge the Unclean', null, null, ['Pure Faith'], null, 'Spend a Fate Point to repel daemons.'),
    new Talent('Quick Draw', null, null, null, null, 'Ready as a Free Action.'),
    new Talent('Rapid Reaction', {'Ag': 40}, null, null, null, 'Test Ag to negate surprise.'),
    new Talent('Rapid Reload', null, null, null, null, 'Reduce reload time.'),
    new Talent('Renowned Warrant', null, null, null, null, 'Provides bonus to Interaction Tests.'),
    new Talent('Resistance (Cold)', null, null, null, null, 'Gain +10 bonus to Resistance Tests.'), 
    new Talent('Resistance (Fear)', null, null, null, null, 'Gain +10 bonus to Resistance Tests.'), 
    new Talent('Resistance (Heat)', null, null, null, null, 'Gain +10 bonus to Resistance Tests.'), 
    new Talent('Resistance (Poisons)', null, null, null, null, 'Gain +10 bonus to Resistance Tests.'), 
    new Talent('Resistance (Psychic Techniques)', null, null, null, null, 'Gain +10 bonus to Resistance Tests.'), 
    new Talent('Rite of Awe', null, null, null, ['Mechanicus Implants'], '50m radius, -10 to all Tests due to fear.'),
    new Talent('Rite of Fear', null, null, null, ['Mechanicus Implants'], 'Fear rating 1 for two minutes in a 50m radius.'),
    new Talent('Rite of Pure Thought', null, null, null, ['Mechanicus Implants'], 'The explorer is immune to emotion.'),
    new Talent('Rite of Sanctioning', null, null, ['Psy Rating'], null, 'Reduces Psychic Phenomenon.'),
    new Talent('Rival (Academics)', null, null, null, null, 'Academics bear the Explorer animosity'), 
    new Talent('Rival (Adepta Sororitas)', null, null, null, null, 'The Adepta Sororitas bears the Explorer animosity'), 
    new Talent('Rival (Adeptus Arbites)', null, null, null, null, 'The Adeptus Arbites bears the Explorer animosity'), 
    new Talent('Rival (Adeptus Mechanicus)', null, null, null, null, 'The Adeptus Mechanicus bears the Explorer animosity'), 
    new Talent('Rival (Administratum)', null, null, null, null, 'The Administratum bears the Explorer animosity'), 
    new Talent('Rival (Astropaths)', null, null, null, null, 'Astropaths bear the Explorer animosity'), 
    new Talent('Rival (Ecclesiarchy)', null, null, null, null, 'The Ecclesiarchy bears the Explorer animosity'), 
    new Talent('Rival (Government)', null, null, null, null, 'A Government bears the Explorer animosity'), 
    new Talent('Rival (Imperial guard)', null, null, null, null, 'The Imperial Guard bears the Explorer animosity'), 
    new Talent('Rival (Imperial Navy)', null, null, null, null, 'The Imperial Navy bears the Explorer animosity'), 
    new Talent('Rival (Inquisition)', null, null, null, null, 'The Inquisition bears the Explorer animosity'), 
    new Talent('Rival (Middle Classes)', null, null, null, null, 'The Middle Classes bear the Explorer animosity'), 
    new Talent('Rival (Military)', null, null, null, null, 'A Military bears the Explorer animosity'), 
    new Talent('Rival (Navigators)', null, null, null, null, 'Navigators bear the Explorer animosity'), 
    new Talent('Rival (Nobility)', null, null, null, null, 'Nobility bears the Explorer animosity'), 
    new Talent('Rival (Rogue Traders)', null, null, null, null, 'Rogue Traders bear the Explorer animosity'), 
    new Talent('Rival (Underworld)', null, null, null, null, 'The Underworld bears the Explorer animosity'), 
    new Talent('Rival (Workers)', null, null, null, null, 'Workers bear the Explorer animosity'), 
    new Talent('Sharpshooter', {'BS': 40}, null, ['Deadeye Shot'], null, 'No Penalties for called shots.'),
    new Talent('Sound Constitution', null, null, null, null, 'Gain an additional Wound.'),
    new Talent('Sprint', null, null, null, null, 'Move more quickly in combat.'),
    new Talent('Step Aside', {'Ag': 40}, ['Dodge'], null, null, 'Gain an extra Dodge each Round.'),
    new Talent('Strong Minded', {'WS': 30}, null, ['Resistance (Psychic Techniques)'], null, 'Re-roll failed WP Tests made to resist Psychic Techniques.'),
    new Talent('Sure Strike', {'WS': 30}, null, null, null, 'Choose location on a successful attack.'),
    new Talent('Swift Attack', {'WS': 35}, null, null, null, 'Attack twice with a Full Action.'),
    new Talent('Takedown', null, null, null, null, 'Make a special attack to stun the Explorer\'s opponent.'),
    new Talent('Talented', null, null, null, null, 'Gain +10 bonus to corresponding Skill Test.'), 
    new Talent('Technical Knock', {'Int': 30}, null, null, null, 'Un-jam a gun as a Half Action.'),
    new Talent('The Emperor Protects', null, null, ['Pure Faith'], null, 'Spend a Fate Point to inspire fealessness and heroism.'),
    new Talent('The Flesh is Weak', null, null, null, ['Mechanicus Implants'], 'The Explorer gains the Machine Trait.'),
    new Talent('Thrown Weapon Training (Universal)', null, null, null, null, 'Gain proficiency with a group of thrown weapons.'), 
    new Talent('Total Recall', {'Int': 30}, null, null, null, 'The Explorer can remember trivial facts and minor details.'),
    new Talent('True Grit', {'T': 40}, null, null, null, 'Reduce Critical damage the Explorer takes.'),
    new Talent('Two-Weapon Wielder (Melee)', {'WS': 35, 'Ag': 35}, null, null, null, 'Attack twice when wielding two weapons.'),
    new Talent('Two-Weapon Wielder (Ballistic)', {'BS': 35, 'Ag': 35}, null, null, null, 'Attack twice when wielding two weapons.'),
    new Talent('Unarmed Master', {'WS': 45, 'Ag': 40}, null, ['Unarmed Warrior'], null, 'Attacks do 1D10+SB damage and lack the Primative trait.'),
    new Talent('Unarmed Warrior', {'WS': 35, 'Ag': 35}, null, null, null, 'Deal 1D10-3+SB with unarmed attacks.'),
    new Talent('Unremarkable', null, null, null, null, 'The Explorer is easily forgettable.'),
    new Talent('Unshakeable Faith', null, null, null, null, 'The Explorer may re-roll failed Fear Tests.'),
    new Talent('Void Tactician', {'Int': 35}, null, null, null, 'Grants a bonus to starship combat.'),
    new Talent('Wall of Steel', {'Ag': 30}, null, null, null, 'Gain extra Parry Each round.'),
    new Talent('Warp Affinity', null, null, ['Psy Rating'], null, 'Re-roll Psychic Phenomena.'),
    new Talent('Warp Conduit', {'WP': 50}, null, ['Psy Rating', 'Strong Minded'], null, '+1 to Psy Rating when pushing.'),
    new Talent('Warp Sense', {'Per': 30}, ['Psyniscience'], ['Navigator', 'Psy Rating'], null, 'Allows Psyniscience Test as Half Action.'),
    new Talent('Whispers', {'Int': 40, 'Fel': 30}, null, null, null, 'Provides Bonuses to Investigations.'),
    new Talent('Wrath of the Righteous', null, null, ['Pure Faith'], null, "Spend a Fate Point to deal extra Damage."),
]